[libraries]
papermc = "io.papermc.paper:paper-api:1.21.10-R0.1-SNAPSHOT"
vault = "com.github.MilkBowl:VaultAPI:1.7"
papi = "me.clip:placeholderapi:2.11.6"

[plugins]
shadow = "com.gradleup.shadow:8.3.6"