# Options available: 'en' | 'pt'.
lang: 'en'

teleporter:
  # Maximum delay a teleportation may take, in seconds.
  # This value works together with the permission 'warps.teleporter.delay.<0::max-delay>'.
  max-delay-seconds: 3
  # If false, ongoing teleportations will be cancelled if movement is detected.
  movement-allowed: false
  # If false, ongoing teleportations will be cancelled if damage is detected.
  damage-allowed: false
  # Choose which commands are allowed during teleportation.
  # Options: 'true' | 'false' | 'whitelist' | 'blacklist'.
  # Default is whitelist.
  commands-allowed:
    mode: whitelist
    list: [ 'a', 'f', 'g', '.', 'tell', 'tpcancel' ]

homes:
  # Maximum number of homes a player may own.
  # This value works together with the permission 'warps.homes.limit.<0::max-limit>'.
  max-limit: 5

users:
  # How many days a player may be offline before their data is wiped out (-1 to disable).
  purge-days: 90
  # Autosave in minutes.
  autosave-minutes: 15

tpask:
  # Duration in seconds until a teleportation request expires.
  duration-seconds: 75
  # Minimum delay a teleportation may take, in seconds.
  # This allows every player to cancel the teleportation if they don't want
  # to teleport at the moment the request was accepted.
  min-delay-seconds: 2